// -*- C++ -*- generated by wxGlade 0.3.5.1 on Sun Apr 24 21:57:57 2005

#include "ss_gui.h"


MainFrame::MainFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: MainFrame::MainFrame
    notebook_1 = new wxNotebook(this, -1, wxDefaultPosition, wxDefaultSize, 0);
    notebook_1_pane_4 = new wxPanel(notebook_1, -1);
    notebook_1_pane_2 = new wxPanel(notebook_1, -1);
    notebook_1_pane_1 = new wxPanel(notebook_1, -1);
    frame_1_menubar = new wxMenuBar();
    SetMenuBar(frame_1_menubar);
    wxMenu* wxglade_tmp_menu_1 = new wxMenu();
    wxglade_tmp_menu_1->Append(wxNewId(), wxT("Open"), wxT(""), wxITEM_NORMAL);
    wxglade_tmp_menu_1->Append(wxNewId(), wxT("Save"), wxT(""), wxITEM_NORMAL);
    wxglade_tmp_menu_1->Append(wxNewId(), wxT("Exit"), wxT(""), wxITEM_NORMAL);
    frame_1_menubar->Append(wxglade_tmp_menu_1, wxT("File"));
    wxMenu* wxglade_tmp_menu_2 = new wxMenu();
    wxglade_tmp_menu_2->Append(wxNewId(), wxT("Cut"), wxT(""), wxITEM_NORMAL);
    wxglade_tmp_menu_2->Append(wxNewId(), wxT("Copy"), wxT(""), wxITEM_NORMAL);
    wxglade_tmp_menu_2->Append(wxNewId(), wxT("Paste"), wxT(""), wxITEM_NORMAL);
    frame_1_menubar->Append(wxglade_tmp_menu_2, wxT("Edit"));
    wxMenu* wxglade_tmp_menu_3 = new wxMenu();
    wxglade_tmp_menu_3->Append(wxNewId(), wxT("Connect"), wxT(""), wxITEM_NORMAL);
    wxglade_tmp_menu_3->Append(wxNewId(), wxT("Scan"), wxT(""), wxITEM_NORMAL);
    frame_1_menubar->Append(wxglade_tmp_menu_3, wxT("Tools"));
    wxMenu* wxglade_tmp_menu_4 = new wxMenu();
    wxglade_tmp_menu_4->Append(wxNewId(), wxT("Yourself"), wxT(""), wxITEM_NORMAL);
    frame_1_menubar->Append(wxglade_tmp_menu_4, wxT("Help"));
    frame_1_statusbar = CreateStatusBar(1, 0);
    bitmap_ss_logo = new wxStaticBitmap(this, -1, wxBitmap(wxT("C:\\ss_gui\\stripe-snoop-logo.jpg"), wxBITMAP_TYPE_ANY));
    label_2 = new wxStaticText(notebook_1_pane_1, -1, wxT("Connected to:"));
    label_3 = new wxStaticText(notebook_1_pane_1, -1, wxT("Last Command:"));
    label_4 = new wxStaticText(notebook_1_pane_1, -1, wxT("Status:"));
    text_ctrl_server_addr = new wxTextCtrl(notebook_1_pane_1, -1, wxT("127.0.0.1:636828"), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_last_cmd = new wxTextCtrl(notebook_1_pane_1, -1, wxT("Scan Card"), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_status = new wxTextCtrl(notebook_1_pane_1, -1, wxT("Connected"), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    panel_3 = new wxPanel(notebook_1_pane_1, -1);
    panel_4 = new wxPanel(notebook_1_pane_1, -1);
    text_ctrl_scan_l1 = new wxTextCtrl(notebook_1_pane_2, -1, wxT("Card Type:"), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_scan_r1 = new wxTextCtrl(notebook_1_pane_2, -1, wxT("CapitalOne Visa"), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_scan_l2 = new wxTextCtrl(notebook_1_pane_2, -1, wxT("Account Number:"), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_scan_r2 = new wxTextCtrl(notebook_1_pane_2, -1, wxT("4123 4435 2673 1542"), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_scan_l3 = new wxTextCtrl(notebook_1_pane_2, -1, wxT("Expiration:"), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_scan_r3 = new wxTextCtrl(notebook_1_pane_2, -1, wxT("02/2002"), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_scan_l4 = new wxTextCtrl(notebook_1_pane_2, -1, wxT("Name:"), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_scan_r4 = new wxTextCtrl(notebook_1_pane_2, -1, wxT("Joe Mama"), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_scan_l5 = new wxTextCtrl(notebook_1_pane_2, -1, wxT("Encrypted PIN:"), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_scan_r5 = new wxTextCtrl(notebook_1_pane_2, -1, wxT("9542"), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_scan_l6 = new wxTextCtrl(notebook_1_pane_2, -1, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_scan_r6 = new wxTextCtrl(notebook_1_pane_2, -1, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_scan_l7 = new wxTextCtrl(notebook_1_pane_2, -1, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_scan_r7 = new wxTextCtrl(notebook_1_pane_2, -1, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_scan_l8 = new wxTextCtrl(notebook_1_pane_2, -1, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_scan_r8 = new wxTextCtrl(notebook_1_pane_2, -1, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_READONLY);
    text_ctrl_raw_r = new wxTextCtrl(notebook_1_pane_4, -1, wxT(""), wxDefaultPosition, wxDefaultSize, wxTE_READONLY|wxHSCROLL);

    set_properties();
    do_layout();
    // end wxGlade
}


void MainFrame::set_properties()
{
    // begin wxGlade: MainFrame::set_properties
    SetTitle(wxT("Stripe Snoop"));
    int frame_1_statusbar_widths[] = { -1 };
    frame_1_statusbar->SetStatusWidths(1, frame_1_statusbar_widths);
    const wxString frame_1_statusbar_fields[] = {
        wxT("Status: Connected")
    };
    for(int i = 0; i < frame_1_statusbar->GetFieldsCount(); ++i) {
        frame_1_statusbar->SetStatusText(frame_1_statusbar_fields[i], i);
    }
    bitmap_ss_logo->SetToolTip(wxT("Stripe Snoop by Acidus"));
    text_ctrl_server_addr->SetToolTip(wxT("Stripe Snoop Server"));
    text_ctrl_last_cmd->SetToolTip(wxT("Last Command Executed"));
    text_ctrl_status->SetToolTip(wxT("Current Status"));
    text_ctrl_raw_r->SetToolTip(wxT("Raw Output From Stripe Snoop Daemon"));
    // end wxGlade
}


void MainFrame::do_layout()
{
    // begin wxGlade: MainFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    wxGridSizer* grid_sizer_9 = new wxGridSizer(8, 2, 0, 0);
    wxGridSizer* grid_sizer_3 = new wxGridSizer(2, 2, 0, 0);
    wxGridSizer* grid_sizer_5 = new wxGridSizer(3, 1, 0, 0);
    wxGridSizer* grid_sizer_4 = new wxGridSizer(3, 1, 0, 0);
    sizer_1->Add(bitmap_ss_logo, 0, wxEXPAND|wxALIGN_CENTER_HORIZONTAL|wxFIXED_MINSIZE, 0);
    grid_sizer_4->Add(label_2, 0, wxFIXED_MINSIZE, 0);
    grid_sizer_4->Add(label_3, 0, wxFIXED_MINSIZE, 0);
    grid_sizer_4->Add(label_4, 0, wxFIXED_MINSIZE, 0);
    grid_sizer_3->Add(grid_sizer_4, 1, wxEXPAND, 0);
    grid_sizer_5->Add(text_ctrl_server_addr, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_5->Add(text_ctrl_last_cmd, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_5->Add(text_ctrl_status, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_3->Add(grid_sizer_5, 1, wxEXPAND, 0);
    grid_sizer_3->Add(panel_3, 1, wxEXPAND, 0);
    grid_sizer_3->Add(panel_4, 1, wxEXPAND, 0);
    notebook_1_pane_1->SetAutoLayout(true);
    notebook_1_pane_1->SetSizer(grid_sizer_3);
    grid_sizer_3->Fit(notebook_1_pane_1);
    grid_sizer_3->SetSizeHints(notebook_1_pane_1);
    grid_sizer_9->Add(text_ctrl_scan_l1, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_9->Add(text_ctrl_scan_r1, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_9->Add(text_ctrl_scan_l2, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_9->Add(text_ctrl_scan_r2, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_9->Add(text_ctrl_scan_l3, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_9->Add(text_ctrl_scan_r3, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_9->Add(text_ctrl_scan_l4, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_9->Add(text_ctrl_scan_r4, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_9->Add(text_ctrl_scan_l5, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_9->Add(text_ctrl_scan_r5, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_9->Add(text_ctrl_scan_l6, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_9->Add(text_ctrl_scan_r6, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_9->Add(text_ctrl_scan_l7, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_9->Add(text_ctrl_scan_r7, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_9->Add(text_ctrl_scan_l8, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    grid_sizer_9->Add(text_ctrl_scan_r8, 0, wxEXPAND|wxFIXED_MINSIZE, 0);
    notebook_1_pane_2->SetAutoLayout(true);
    notebook_1_pane_2->SetSizer(grid_sizer_9);
    grid_sizer_9->Fit(notebook_1_pane_2);
    grid_sizer_9->SetSizeHints(notebook_1_pane_2);
    sizer_3->Add(text_ctrl_raw_r, 1, wxEXPAND, 0);
    notebook_1_pane_4->SetAutoLayout(true);
    notebook_1_pane_4->SetSizer(sizer_3);
    sizer_3->Fit(notebook_1_pane_4);
    sizer_3->SetSizeHints(notebook_1_pane_4);
    notebook_1->AddPage(notebook_1_pane_1, wxT("Status"));
    notebook_1->AddPage(notebook_1_pane_2, wxT("Scan"));
    notebook_1->AddPage(notebook_1_pane_4, wxT("Raw"));
    sizer_1->Add(new wxNotebookSizer(notebook_1), 1, wxEXPAND, 0);
    SetAutoLayout(true);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    sizer_1->SetSizeHints(this);
    Layout();
    // end wxGlade
}



class MyApp: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(MyApp)

bool MyApp::OnInit()
{
    wxInitAllImageHandlers();
    MainFrame* frame_1 = new MainFrame(0, -1, "");
    SetTopWindow(frame_1);
    frame_1->Show();
    return true;
}






